package com.dhl.clearance;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CategorizationResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@JsonProperty("Value")
	private java.lang.Integer value;
	@JsonProperty("Category")
	private java.lang.String category;

	public CategorizationRequest() {
	}

	public java.lang.Integer getValue() {
		return this.value;
	}

	public void setValue(java.lang.Integer value) {
		this.value = value;
	}

	public CategorizationRequest(java.lang.Integer value,java.lang.String category) {
		this.value = value;
		this.category = category;
	}

	public java.lang.String getCategory() {
		return category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}
}