package com.dhl.clearance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CategorizationRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CategorizationRequest() {
    }




}