package com.dhl.clearance;

/**
 * This class was automatically generated by the data modeler tool.
 */
import java.util.Date;
import java.util.Random;
import com.github.javafaker.Faker;

public class DummyService {

    public static String hello(String name) throws Exception {
        // System.out.println(Thread.currentThread().getName() + " Service invoked with name " + name);
        return "Hello " + name + "!";
    }
    
    public static String enrichment(String trackingNumber) throws Exception {
        Fakerm faker = new Faker();
        return faker.country().name();
    }    
 
     public static Integer valuation(String trackingNumber) throws Exception {
        Random random = new Random();
        Integer value = random.nextInt(3000);
        return value;
    }      
    

}