package com.dhl.clearance;

/**
 * This class was automatically generated by the data modeler tool.
 */
import java.util.Date;


public class DummyService implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public String hello(String name) {
        System.out.println(Thread.currentThread().getName() + " Service invoked with name " + name);
        return "Hello " + name + "!";
    }

}