package com.dhl.clearance;

/**
 * This class was automatically generated by the data modeler tool.
 */
import java.util.Date;


public class DummyService {

    public static String hello(String name) throws Exception {
        System.out.println(Thread.currentThread().getName() + " Service invoked with name " + name);
        return "Hello " + name + "!";
    }

}